name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Railway
        uses: docker://ghcr.io/railwayapp/cli:latest
        with:
          args: |
            link --project ${{ secrets.RAILWAY_PROJECT_ID }} --service backend
            up --service backend
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}