name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v2
        with:
          apiKey: ${{ secrets.RAILWAY_API_KEY }}
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}