name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | bash

      - name: Deploy to Railway
        run: |
          echo ${{ secrets.RAILWAY_API_KEY }} | railway login --token
          railway up --service=backend
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
